Remove tempsort prefix from temp samtools sorts.
Merging from temporary partially-sorted bam files on disk fails with -o unless you use a temporary file path, which is very finicky. Here is the previous error from the alignment log:

```
[bam_sort_core] merging from 5 files...
open: No such file or directory
[bam_merge_core] fail to open file tempsort_/home/ubuntu/millstone/genome_designer/conf/../temp_data/projects/39ac8073/alignment_groups/93410ffd/sample_alignments/4befd396/bwa_align.sorted.bam.0000.bam
[bam_header_read] invalid BAM binary header (this is not a BAM file).
Segmentation fault (core dumped)
Traceback (most recent call last):
  File "/home/ubuntu/millstone/genome_designer/pipeline/read_alignment.py", line 155, in align_with_bwa_mem
    alignment_group.reference_genome, output_bam, error_output)
  File "/home/ubuntu/millstone/genome_designer/pipeline/read_alignment.py", line 291, in process_sam_bam_file
    subprocess.check_call(sort_rmdup_cmd, shell=True, stderr=error_output)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '/home/ubuntu/millstone/genome_designer/conf/../tools/samtools/samtools sort -o /home/ubuntu/millstone/genome_designer/conf/../temp_data/projects/39ac8073/alignment_groups/93410ffd/sample_alignments/4befd396/bwa_align.bam tempsort_/home/ubuntu/millstone/genome_designer/conf/../temp_data/projects/39ac8073/alignment_groups/93410ffd/sample_alignments/4befd396/bwa_align.sorted.bam|/home/ubuntu/millstone/genome_designer/conf/../tools/samtools/samtools rmdup - /home/ubuntu/millstone/genome_designer/conf/../temp_data/projects/39ac8073/alignment_groups/93410ffd/sample_alignments/4befd396/bwa_align.sorted.bam' returned non-zero exit status 139
```

Removing the `tempsort_` prefix solved the problem on ReColi, but I don't want to overwrite the actual sorted output, so I am using a `.tmp.bam` suffix instead.